[workspace]
members = ["crates/crabxl", "crates/crabxl-core", "crates/crabxl-xlsx"]
resolver = "2"

[workspace.package]
version = "0.1.0-alpha.10"
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/crabxl/crabxl"

[workspace.dependencies]
crabxl-core = { path = "crates/crabxl-core", version = "=0.1.0-alpha.10" }
crabxl-xlsx = { path = "crates/crabxl-xlsx", version = "=0.1.0-alpha.10", default-features = false }
zip = { version = "8.6", default-features = false }
quick-xml = "0.42.0"
fast-float2 = "0.2"
percent-encoding = "2.3"
tempfile = "3.27"
chrono = { version = "0.4", default-features = false, features = ["std"] }

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
unwrap_used = "warn"
expect_used = "warn"

[profile.release]
lto = "thin"
